exports.replace_items = {
  stu_name: '',
  major: '',
  class: '',
  stu_id: '',
  teacher_name: '',
  title: '',

  paperTitle: '',
  topic1: '',
  topic2: '',
  topic3: '',

  task: '',
  guide: '',

  startScore1: '',
  startScore2: '',
  startScore3: '',
  startScore: '',
  transScore1: '',
  transScore2: '',
  transScore3: '',
  transScore: '',
  midScore1: '',
  midScore2: '',
  midScore3: '',
  midScore: '',
  midEva: '',
  teachScore1: '',
  teachScore2: '',
  teachScore3: '',
  teachScore4: '',
  teachScore5: '',
  teachScore: '',
  teachEva: '',
  readScore1: '',
  readScore2: '',
  readScore3: '',
  readScore4: '',
  readScore: '',
  readEva: '',
  defScore1: '',
  defScore2: '',
  defScore3: '',
  defScore4: '',
  defScore: '',
  defEva: '',
  defRecord: '',
  finalScore: '',
  rank: '',
  finalEva: '',

  guide_name: '',
  read_name: '',
  leader_name: ''
};
